snowsql_config_path = "/Users/taylor.larson/snowflake/repos/sfguide-data-engineering-with-snowpark-python/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(temp_f float)"
return_type = "float"
file = "app.zip"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "HOL_DB"
schema = "ANALYTICS"
warehouse = "HOL_WH"
role = "HOL_ROLE"
overwrite = true
